logging:
  level:
    root: INFO

server:
  port: ${SERVER_PORT:8082}

spring:
  cloud:
    config:
      enabled: false
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}
      timeout: ${REDIS_TIMEOUT:5s}
      connect-timeout: ${REDIS_CONNECT_TIMEOUT:10s}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/core_db}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${DB_USERNAME:core_user}
    password: ${DB_PASSWORD:core_pass}

  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    displayRequestDuration: true
    enabled: true