spring:
  application:
    name: core-service
  
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      enabled: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      repositories:
        enabled: false 
        
  cache:
    type: redis
    redis:
      time-to-live: 1h
      use-key-prefix: true

server:
  port: 8082

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true